### ISSUE TITLE
Logs stop showing up after a while

### ISSUE THREAD

**Issue by jahio** [joshsoftware/minion-streamserver#1]
<img width="2672" alt="Screen Shot 2020-06-26 at 11 28 53 AM" src="https://user-images.githubusercontent.com/421850/85884665-3c261300-b7a0-11ea-992b-8baacaf35d02.png">

After running the streamserver for a while, eventually logs stop showing up. In this screenshot above I'm tailing `/var/log/system.log` on MacOS. You can see that it's sending log data to the streamserver (running top right), but that streamserver isn't displaying the log output.

I even did an echo "Hello World" into that log, and we see that it's being sent in the screenshot, but it never displays in the streamserver output.

If this is just an output bug, no problem, but if there's a real problem with it acknowledging/receiving the log line data, we need to figure out what's going on.

**Comment by jahio** [comment]
Quick notes I forgot to mention:

+ The telemetry (CPU/MEM) is sent every 5 seconds.
+ The very first time logs were sent, the streamserver _did_ pick that up and show that.

**Comment by wyhaines** [comment]
The only way that I have been able to recreate this is through a bug in the client, which should be fixed now.  I'm going to close this, and will reopen if I am able to deterministically recreate a scenario for it.

**Comment by wyhaines** [comment]
This is connected to https://github.com/joshsoftware/minion-agent/issues/24

**Comment by wyhaines** [comment]
This is resolved as per the https://github.com/joshsoftware/minion-agent/issues/24 issue.
